spring:
  datasource:
    url: jdbc:postgresql://10.78.16.20:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    spring: info
    database: info
    http: info
  file:
    name: ""